export const EQUIPMENT_MAP: Record<string, string> = {
  "body weight": "none",
  "bodyweight": "none",
  "no equipment": "none",
  "dumbbell": "dumbbells",
  "dumbbells": "dumbbells",
  "pair of dumbbells": "dumbbells",
  "barbell": "barbell",
  "barbells": "barbell",
  "band": "resistance-band",
  "resistance band": "resistance-band",
  "resistance bands": "resistance-band",
  "exercise ball": "exercise-ball",
  "stability ball": "exercise-ball",
  "yoga ball": "exercise-ball",
  "bench": "bench",
  "flat bench": "bench",
  "incline bench": "bench",
  "weight bench": "bench",
  "pull-up bar": "pull-up-bar",
  "pullup bar": "pull-up-bar",
  "cable": "cable-machine",
  "cable machine": "cable-machine",
  "kettlebell": "kettlebell",
  "kettlebells": "kettlebell",
  "foam roll": "foam-roller",
  "foam roller": "foam-roller",
  "mat": "mat",
  "exercise mat": "mat",
  "yoga mat": "mat",
  "step platform": "step-platform",
  "step": "step-platform",
  "ab roller": "ab-roller",
  "ab-wheel": "ab-roller",
  "rope": "jump-rope",
  "jump rope": "jump-rope",
  "box": "plyometric-box",
  "plyometric box": "plyometric-box",
  "medicine ball": "medicine-ball",
  "hammer": "sledgehammer",
  "sledgehammer": "sledgehammer",
  "wheel roller": "ab-roller",
  "skierg": "ski-erg",
  "ski erg": "ski-erg",
  "assisted": "pull-up-bar",
};

export const EQUIPMENT_SLUGS = [
  "none",
  "dumbbells",
  "barbell",
  "resistance-band",
  "exercise-ball",
  "bench",
  "pull-up-bar",
  "cable-machine",
  "kettlebell",
  "foam-roller",
  "mat",
  "step-platform",
  "ab-roller",
  "jump-rope",
  "plyometric-box",
  "medicine-ball",
  "sledgehammer",
  "ski-erg",
] as const;
