export const MUSCLE_MAP: Record<string, string> = {
  "pectorals": "pectorals",
  "chest": "pectorals",
  "biceps": "biceps",
  "triceps": "triceps",
  "delts": "deltoids",
  "deltoids": "deltoids",
  "shoulders": "deltoids",
  "forearms": "forearms",
  "abs": "abs",
  "abdominals": "abs",
  "obliques": "obliques",
  "glutes": "glutes",
  "buttocks": "glutes",
  "quadriceps": "quadriceps",
  "quads": "quadriceps",
  "hamstrings": "hamstrings",
  "calves": "calves",
  "trapezius": "trapezius",
  "traps": "trapezius",
  "upper back": "upper-back",
  "lats": "latissimus-dorsi",
  "latissimus dorsi": "latissimus-dorsi",
  "lower back": "lower-back",
  "spine": "lower-back",
  "hip flexors": "hip-flexors",
  "inner thigh": "adductors",
  "adductors": "adductors",
  "abductors": "abductors",
  "ankles": "ankles",
  "feet": "feet",
  "neck": "neck",
  "rotator cuff": "rotator-cuff",
  "upper legs": "quadriceps",
  "lower legs": "calves",
  "cardiovascular system": "cardiovascular",
  "cardio": "cardiovascular",
  "core": "abs",
};

export const MUSCLE_SLUGS = [
  "pectorals",
  "biceps",
  "triceps",
  "deltoids",
  "forearms",
  "abs",
  "obliques",
  "glutes",
  "quadriceps",
  "hamstrings",
  "calves",
  "trapezius",
  "upper-back",
  "latissimus-dorsi",
  "lower-back",
  "hip-flexors",
  "adductors",
  "abductors",
  "ankles",
  "feet",
  "neck",
  "rotator-cuff",
  "cardiovascular",
] as const;
